### ISSUE TITLE
Ablation Study

### ISSUE THREAD

**Issue by catherinezll95** [wei-mao-2019/LearnTrajDep#10]
Thanks for your code sharing.
In Ablation Study, the paper mentioned the experiment of using a pre-defined adjacency matrix based on the kinematic tree. In the code, I found that you regard the position(x, y, z) of one node as three nodes in your graph. So I am curious about when you use a pre-defined adjacency matrix, you regard (x, y, z) as the attribute rather than three nodes? It means that the input nodes are 22 rather than 66 in your 3D training.

**Comment by wei-mao-2019** [comment]
Hi @catherinezll95,

I use 66 nodes thus (x, y, z) as 3 nodes.

Thank you
