### ISSUE TITLE
Re-training 3dPW model

### ISSUE THREAD

**Issue by hassony2** [wei-mao-2019/LearnTrajDep#11]
Hi !

Thank you for your great work on human pose prediction.
I am trying to re-train models, more specifically the 3DPW dataset in 3D space.
For this, I am using a more recent version of PyTorch (1.4) and I find that my results are slightly lower than the ones you report. In order to help me track down the discrepancy, I was wondering if you would be able to provide a full log-file for one of the training runs, and maybe the corresponding pre-trained model ?

All the best !

Yana

**Comment by wei-mao-2019** [comment]
Hi,

Sorry, I did not save the log-file. Can you show me your results? If it is not significantly different it should be fine. As I showed in this repo, I trained the same model 3 times and the final results are slightly different.

Cheers
Wei
