### ISSUE TITLE
About the visualization

### ISSUE THREAD

**Issue by Xianjin111** [wei-mao-2019/LearnTrajDep#3]
Thank you for your perfect work. I have a problem about the visualization as following, 
Traceback (most recent call last):
  File "demo.py", line 106, in <module>
    main(option)
  File "demo.py", line 58, in main
    sample_rate=sample_rate, is_norm_dct=opt.is_norm_dct, is_norm=opt.is_norm )
TypeError: __init__() got an unexpected keyword argument 'is_norm_dct'

In order to deal with it , I just changed 57 lines in demo.py to test_dataset = H36motion(path_to_data=opt.data_dir, actions=act, input_n=input_n, output_n=output_n, split=1, sample_rate=sample_rate, dct_n=dct_n)

It still has problem as following:
Traceback (most recent call last):
  File "demo.py", line 106, in <module>
    main(option)
  File "demo.py", line 74, in main
    for i, (inputs, targets, all_seq, one_hot) in enumerate(test_data[act]):
ValueError: not enough values to unpack (expected 4, got 3)

So could you please help me to deal with the problem? Thank you very much.

**Comment by wei-mao-2019** [comment]
Thank you. 

I have update the demo.py file. It should be alright now.

Cheers
Wei

**Comment by Xianjin111** [comment]
> Thank you.
> 
> I have updated the demo.py file. It should be alright now.
> 
> Cheers
> Wei

It works！ Thank you so much!
