### ISSUE TITLE
experiment hyper-parameters (commands) to reproduce your results on 3DPW dataset

### ISSUE THREAD

**Issue by hangg7** [wei-mao-2019/LearnTrajDep#4]
Hi Wei,

Thanks for open-sourcing this work! I'm recently trying to reproduce your results on angle and position setting as included in the README. But I kinda stuggle to find out your exact hyper-parameters/commands for those numbers. 

Can you please share your hyper-paremters or, even better, the running commands with `main_3dpw*.py`/pretrained models?

**Comment by wei-mao-2019** [comment]
Hi @hangg7,

I just updated the readme file. Running args we used for training is included.

Thank you
Cheers
