### ISSUE TITLE
Pretrained Model

### ISSUE THREAD

**Issue by DanLuoNEU** [wei-mao-2019/LearnTrajDep#7]
Thanks for sharing the great project!

But I am wondering if you can share the pretrained model from your team, so we can save the training time. It would really help a lot.

**Comment by wei-mao-2019** [comment]
Hi @DanLuoNEU,

The pretrained model for human 3.6M is provided in the repo. As to cmu and 3dpw, it should be pretty fast to train a new model (a few hours or less). 

The evaluation code is already provided in the training code. I commented out the training code to make it a eval code. You can do the same for 3dpw and cmu.

Cheers
Wei
