### ISSUE TITLE
About Visualization of 3D data

### ISSUE THREAD

**Issue by DanLuoNEU** [wei-mao-2019/LearnTrajDep#8]
As it is mentioned in the paper, when you are using 3D data to train the network, you eliminate the Global Rotation and Translation, which are the first 6 dimensions of the exponential map. 
```python 
# remove global rotation and translation
the_seq[:, 0:6] = 0
p3d = expmap2xyz_torch(the_seq)
```
So when I am using your training or testing 3D data to do the visualization, the whole skeleton is a sloping one. Like the figure below shows:
![image](https://user-images.githubusercontent.com/56852645/68911278-63a10180-0722-11ea-87e8-84a2aa81325b.png)
But as you show in the paper, the skeleton is totally fine, would you help me with some tools or codes that you use to generate a normal skeleton from your training or test 3D data?

**Comment by wei-mao-2019** [comment]
Hi @DanLuoNEU,

I think you may need to adjust the view point if you are using matplotlib.pyplot. You can check the official document for that.

Cheers
Wei
